<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-O2A86F5" failures="1" tests="2" name="Test(failed)" time="0.132" errors="0" timestamp="2022-08-29T16:18:39 IST">
  <testcase classname="testNG_example.failed_test" name="m4" time="0.024">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG_example.failed_test.m4(failed_test.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- m4 -->
  <testcase classname="testNG_example.failed_test" name="m5" time="0.003"/>
  <testcase classname="testNG_example.failed_test" name="m2" time="0.0">
    <ignored/>
  </testcase> <!-- m2 -->
  <testcase classname="testNG_example.failed_test" name="m3" time="0.0">
    <ignored/>
  </testcase> <!-- m3 -->
  <testcase classname="testNG_example.failed_test" name="m1" time="0.0">
    <ignored/>
  </testcase> <!-- m1 -->
</testsuite> <!-- Test(failed) -->
